### ISSUE TITLE
meteor-ios-launch-screen-fix

### ISSUE THREAD

**Issue by mjwheatley** [cunneen/meteor-ios-icon-fix#2]
Is there a similar fix for launch screen images?

I have added my own launch screens to replace the default meteor images, but there is still one outlying cordova image.

1x for iPhone Portrait iOS 5,6 `Default~iphone.png` 320x480

This seems to be a legacy launch screen that you can no longer specify in `mobile-config.js`

http://docs.meteor.com/api/mobile-config.html#App-launchScreens

Could you help add the ability to remove specified launch screen images to this package or perhaps create a new one?

**Comment by cunneen** [comment]
Hi @mjwheatley , you could do this easily enough:

1) Clone (& rename) this plugin
2) Modify Line 16 of the [scripts/afterBuild.js](https://github.com/AppWorkshop/meteor-ios-icon-fix/blob/v1.0.0/scripts/afterBuild.js#L16) to point to the Launch Screens asset catalogue rather than the icons one.
3) Use a different config preference parameter name for Line 22 of [scripts/afterBuild.js](https://github.com/AppWorkshop/meteor-ios-icon-fix/blob/v1.0.0/scripts/afterBuild.js#L22) and default it to a value of `"Default~iphone.png"`

**Comment by mjwheatley** [comment]
I thought it might be good to have all the related packages from the save development team.  I'm using AppWorkshop/meteor-ios-icon-fix and AppWorkshop/cordova-storyboard-image-config.  I was hoping you might be interesting in publishing the new one.
